### ISSUE TITLE
Security problem with your Reddit account

### ISSUE THREAD

**Issue by rememberYou** [3vanlock/dotfiles#1]
First of all, thank you for sharing your dotfiles.

I would like to point out that you have clearly displayed the JSON link to your reddit account, which contains sensitive information and therefore a security problem:
`url="https://www.reddit.com/message/unread/.json?feed=b6ca51e2b6537340f2d95db101969d1536066acc&user=RevReturns"`

Source: [reddit](https://github.com/elock37/dotfiles/blob/604cbb3563ad15d9b1cda6697afd20a9d4f0f02e/polybar/.config/polybar/reddit)

The solution to this would be for you to place this link in a GPG file so that you can easily share it without risk.

Here is a solution I implemented:
```
# Replace this path by yours.
reddit_gpg="/home/$USER/Sync/shared/.reddit-json.gpg"
url="https://www.reddit.com/message/unread/.json?feed=$(gpg -qd "$reddit_gpg")"
```

The complete script is available in my [dotfiles](https://github.com/rememberYou/dotfiles/blob/master/bin/bin/polybar-reddit.sh).

Please remember to change your password so that a new JSON link is regenerated.

**Comment by 3vanlock** [comment]
Issue made obsolete with removal of Reddit notifications in polybar.
